### ISSUE TITLE
v2.0 won't initialize

### ISSUE THREAD

**Issue by alexhutko** [pnsn/squacapi_client#4]
```
(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ 
(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ cat test_v2.py 
#!/home/ahutko/anaconda3/bin/python

import os

# Import modules
try:
    from squacapi_client.models.write_only_measurement_serializer \
    import WriteOnlyMeasurementSerializer
    from squacapi_client.pnsn_utilities \
    import get_client, make_channel_map, make_metric_map, perform_bulk_create
except Exception as e:
    print("Info: squacapi_client not available, cannot use --squac option")

USER = os.environ['SQUACAPI_USER']
PASSWORD = os.environ['SQUACAPI_PASSWD']

# Iniate the client
squac_client = get_client(USER, PASSWORD)

(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ 
(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ ./test_v2.py 
Traceback (most recent call last):
  File "./test_v2.py", line 20, in <module>
    squac_client = get_client(USER, PASSWORD)
  File "/home/ahutko/anaconda3/lib/python3.7/site-packages/squacapi_client/pnsn_utilities.py", line 14, in get_client
    api_client = ApiClient(conf)
  File "/home/ahutko/anaconda3/lib/python3.7/site-packages/squacapi_client/api_client.py", line 78, in __init__
    self.client_side_validation = configuration.client_side_validation
AttributeError: 'Configuration' object has no attribute 'client_side_validation'
(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ 
(squacapi_client_v2) ahutko@namazu:~/proj/STATION_REPORT/DATA_MINING$ 
```

**Comment by alexhutko** [comment]
Seems fixed.
